[extend]
useDefault = true

[allowlist]
description = "Allowlist for test and example files"
paths = [
  '''tests/''',
  '''README.md''',
  '''k8s/secret.yaml''',
  '''app/app_vulnerable.py''',
  '''app/Dockerfile\.vulnerable''',
  '''app/requirements_vulnerable\.txt'''
]